unbind-key -a -T root

set -g default-shell /bin/zsh

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi

set -g mouse on

set -s escape-time 0

set -g history-limit 2000
bind -n M-r source-file ~/.tmux.conf

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-s select-pane -L
bind -n M-f select-pane -R
bind -n M-e select-pane -U
bind -n M-d select-pane -D

bind -n M-Left resize-pane -L 3
bind -n M-Right resize-pane -R 3
bind -n M-Up resize-pane -U 3
bind -n M-Down resize-pane -D 3

bind -n M-k split-window -v
bind -n M-l split-window -h

bind -n M-g previous-window
bind -n M-h next-window

bind -n M-n new-window
bind -n M-j kill-pane
bind -n M-q detach

set -g pane-border-status bottom
set -g pane-border-format "#[fg=blue,bold] #{pane_current_path} " 
set -ga pane-border-format "#[fg=orange,bold]#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null | sed 's/\\(.*\\)/ \\1 /')"

set -g status-left ""
set -g status-right ""
set -g status-left-length 0
set -g status-right-length 0

set -g status on
set -g status-justify left
set -g status-style default

set -g status-left "#[fg=white,bold]  #(echo "$(whoami)@$(hostname)") "
set -ga status-left "#[fg=black,bold] #(top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4\"% \"}')"
set -ga status-left "#[fg=black,bold] #(free -h | grep 'Mem:' | awk '{print $3 \"/\" $2}')  "

set -g status-right "#[fg=white,bold]󰃰 #(date '+%d %B %Y %H:%M') "

set -g status-interval 10

set -g window-status-current-format "#[fg=white,bold] #I"
set -g window-status-format "#[fg=black] #I"
set -g window-status-separator " "

set -g pane-border-style "fg=blue"
set -g pane-active-border-style "fg=blue"

set -g status-keys emacs
set -g status-position bottom
